import { Archetype, Question } from '../types';

export const ARCHETYPES: Archetype[] = [
    {
        id: 'tradicional',
        name: 'El Tradicional Orbital',
        vibe: 'Sos el guardián de la mística, el que sabe que el mate no se apura ni se hierve.',
        ritual: ['Mate caliente', 'Amargo', 'Agua a 75-80°C', 'Cebadas parejas'],
        recommendation: 'Yerba Clásica + Mate de calabaza',
        tip: 'No lo hiervas, no lo mates. La paciencia es tu mejor yerba.',
        image: '/mate_tradicional.png',
    },
    {
        id: 'tereré',
        name: 'La Tereré Explorer',
        vibe: 'Cero complicaciones, mucha frescura. Donde otros ven calor, vos ves una jarra con hielo.',
        ritual: ['Tereré', 'Cítricos o menta', 'Mucho hielo', 'Jarrita de acero o vidrio'],
        recommendation: 'Yerba con Hierbas + Jugo frutal',
        tip: 'Si hace calor, no discutas: tereré. El hielo es tu mejor amigo.',
        image: '/mate_terere.png',
    },
    {
        id: 'intenso',
        name: 'El Intenso de Gravedad',
        vibe: 'Directo al grano. O a la hoja. No buscás charla, buscás que ese primer amargo te reinicie.',
        ritual: ['Amargo fuerte', 'Yerba intensa', 'Mate chico', 'Cebada corta'],
        recommendation: 'Yerba Despalada + Mate de madera',
        tip: 'Pocas palabras. Mucha yerba. La intensidad no se negocia.',
        image: '/mate_intenso.png',
    },
    {
        id: 'dulce',
        name: 'La Dulce Nostálgica',
        vibe: 'El mate es un abrazo. Lo preferís amable, compañero y con ese toque dulce que te transporta.',
        ritual: ['Dulcito (con criterio)', 'Mate grande', 'Ritmo lento', 'Agua templada'],
        recommendation: 'Yerba Suave + Azúcar o miel',
        tip: 'Dulce sí, empalagoso no. El equilibrio es el secreto del cariño.',
        image: '/mate_dulce.png',
    },
    {
        id: 'botánico',
        name: 'El Botánico Cósmico',
        vibe: 'Tu mate es un laboratorio. Cedrón, peperina, lo que sea que le dé ese perfil místico.',
        ritual: ['Yuyos y mezclas', 'Menta o cedrón', 'Mate suave', 'Agua a punto'],
        recommendation: 'Yerba con Mezcla de Hierbas',
        tip: 'Experimentar es parte del rito. Cada yuyo cuenta una historia.',
        image: '/mate_botanico.png',
    },
    {
        id: 'social',
        name: 'El Social de la Galaxia',
        vibe: 'El mate es el centro de tu universo social. No importa la yerba, importa quién está enfrente.',
        ritual: ['Mate compartido', 'Mate grande', 'Termos cerca', 'Conversación eterna'],
        recommendation: 'Yerba Selección Especial + Termo de 1L',
        tip: 'El mate es la excusa: lo importante es la ronda y lo que se dice en ella.',
        image: '/mate_social.png',
    },
    {
        id: 'oficinista',
        name: 'El Oficinista Cósmico',
        vibe: 'El mate es tu excusa para levantarte del escritorio. La cafetera de la oficina te mira con odio.',
        ritual: ['Mate de escritorio', 'Termo escondido', 'Cebadas rápidas', 'Evitar derrames'],
        recommendation: 'Yerba Suave + Mate de acero (anti-derrames)',
        tip: 'El mate productivo es el que te saca del Excel por cinco minutos.',
        image: '/mate_oficinista.png',
    },
    {
        id: 'madrugador',
        name: 'El Madrugador Galáctico',
        vibe: 'Mientras el barrio duerme, vos ya vas por el tercer termo. El sol sale cuando vos querés.',
        ritual: ['Mate a las 5am', 'Silencio total', 'Agua bien caliente', 'Mirar el amanecer'],
        recommendation: 'Yerba Intensa + Mate de calabaza grande',
        tip: 'El que madruga, ceba mejor. Pero ojo con el ruido del termo.',
        image: '/mate_madrugador.png',
    },
    {
        id: 'estudiantil',
        name: 'El Estudiante Eterno',
        vibe: 'El mate es tu compañero de finales. Lo cebás con dedicación inversamente proporcional a tu estudio.',
        ritual: ['Mate nocturno', 'Apuntes cerca', 'Yerba rendidora', 'Procrastinación activa'],
        recommendation: 'Yerba con Energía + Mate grande (para no recargar)',
        tip: 'El mate no te va a aprobar, pero te va a acompañar en el intento.',
        image: '/mate_estudiantil.png',
    },
    {
        id: 'rebelde',
        name: 'El Rebelde Sin Yerba',
        vibe: 'Le ponés lo que se te canta. Yerba mezclada, café, té. La tradición te importa tres pepinos.',
        ritual: ['Mezclas locas', 'Sin reglas', 'Experimentar siempre', 'Romper esquemas'],
        recommendation: 'Yerba + Café + Lo que encuentres',
        tip: 'Las reglas del mate las escriben los que nunca probaron nada nuevo.',
        image: '/mate_rebelde.png',
    },
    {
        id: 'zen',
        name: 'El Zen Pampeano',
        vibe: 'El mate es tu meditación. No apurás, no hablás, solo escuchás el sonido del agua cayendo.',
        ritual: ['Cebada lenta', 'Respiración profunda', 'Silencio', 'Contemplación'],
        recommendation: 'Yerba Orgánica + Mate de cerámica',
        tip: 'El mate perfecto se ceba sin apuro. El tiempo es tu mejor ingrediente.',
        image: '/mate_zen.png',
    },
    {
        id: 'nostalgico',
        name: 'El Nostálgico del Interior',
        vibe: 'Cerrás los ojos y estás en lo de la abuela. El mate te transporta a los domingos de sol.',
        ritual: ['Mate de la familia', 'Yerba de siempre', 'Facturas caseras', 'Recuerdos'],
        recommendation: 'Yerba Clásica + Mate heredado',
        tip: 'El mejor mate es el que te lleva a casa, aunque estés lejos.',
        image: '/mate_nostalgico.png',
    },
];

export const QUESTIONS: Question[] = [
    {
        id: 'q1',
        text: '¿Cuándo mateás más?',
        options: [
            { text: 'A la mañana temprano ☀️', scores: { intenso: 2, tradicional: 1, madrugador: 3 } },
            { text: 'En la oficina/trabajo 💼', scores: { oficinista: 3, social: 1 } },
            { text: 'A la tarde 🌅', scores: { social: 2, dulce: 1, nostalgico: 1 } },
            { text: 'A la noche 🌙', scores: { botánico: 2, estudiantil: 3, zen: 1 } },
        ],
    },
    {
        id: 'q2',
        text: '¿Qué buscás con el mate?',
        options: [
            { text: 'Despertarme ⚡', scores: { intenso: 2, madrugador: 2, oficinista: 1 } },
            { text: 'Paz mental 🧘', scores: { botánico: 2, zen: 3 } },
            { text: 'Aguantar el estudio 📚', scores: { estudiantil: 3, intenso: 1 } },
            { text: 'Salir de la rutina 🤪', scores: { rebelde: 3, social: 1 } },
        ],
    },
    {
        id: 'q3',
        text: '¿Cómo lo preferís?',
        options: [
            { text: 'Amargo y caliente 🌿', scores: { intenso: 2, tradicional: 2, madrugador: 1 }, dominant: 'tradicional' },
            { text: 'Con yuyos o mezclas 🧪', scores: { botánico: 3, rebelde: 2 } },
            { text: 'Dulce 🍯', scores: { dulce: 3, nostalgico: 1 } },
            { text: 'Tereré 🧊', scores: { tereré: 3 } },
        ],
    },
    {
        id: 'q4',
        text: '¿Dónde mateás?',
        options: [
            { text: 'Al aire libre 🌳', scores: { tradicional: 2, zen: 2, tereré: 1 } },
            { text: 'En el escritorio 💻', scores: { oficinista: 3, estudiantil: 2 } },
            { text: 'En la cocina de casa 👵', scores: { nostalgico: 3, dulce: 1 } },
            { text: 'Donde pinte 🤷', scores: { rebelde: 2, social: 1 } },
        ],
    },
    {
        id: 'q5',
        text: '¿Con quién mateás?',
        options: [
            { text: 'Solo/a en paz 👤', scores: { zen: 3, madrugador: 2, intenso: 1 } },
            { text: 'Con amigos 🗣️', scores: { social: 3, rebelde: 1 } },
            { text: 'Con compañeros 🤝', scores: { oficinista: 2, estudiantil: 2 } },
            { text: 'Con la familia 🏠', scores: { nostalgico: 3, tradicional: 1 } },
        ],
    },
    {
        id: 'q6',
        text: 'Si se lava el mate...',
        options: [
            { text: 'Lo cambio de una 🔄', scores: { tradicional: 2, intenso: 2, madrugador: 1 } },
            { text: 'Lo sigo tomando igual 💀', scores: { estudiantil: 3, oficinista: 2 } },
            { text: 'Le tiro café o yuyos ☕', scores: { rebelde: 3, botánico: 1 } },
            { text: 'Me relajo y sigo 🧘', scores: { zen: 2, social: 1 } },
        ],
    },
    {
        id: 'q7',
        text: 'Tu personalidad mate:',
        options: [
            { text: 'Clásico/Conservador 🏛️', scores: { tradicional: 2, nostalgico: 2 } },
            { text: 'Productivo/Manija 🚀', scores: { oficinista: 2, madrugador: 2, estudiantil: 1 } },
            { text: 'Experimental/Loco 🧪', scores: { rebelde: 3, botánico: 1 } },
            { text: 'Chill/Tranqui ✨', scores: { zen: 3, dulce: 1, tereré: 1 } },
        ],
    },
];
